#!/Users/szammy/.local/share/mise/installs/lua/5.4.7/bin/lua

local config_dir = os.getenv("HOME") .. "/.config/sketchybar"

-- Prepend the configuration directory to the module search paths
package.path = config_dir .. "/?.lua;" .. config_dir .. "/?/init.lua;" .. package.path
package.cpath = config_dir .. "/?.so;" .. package.cpath

package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

require("init")
